WellCommerce\Bundle\CompanyBundle\Entity\CompanyAddress:
    fields:
        line1:
            groups:
                - default
                - company_address
        line2:
            groups:
                - default
                - company_address
        postalCode:
            groups:
                - default
                - company_address
        state:
            groups:
                - default
                - company_address
        city:
            groups:
                - default
                - company_address
        country:
            groups:
                - default
                - company_address
    associations: {  }
    callbacks: {  }
