WellCommerce\Bundle\CompanyBundle\Entity\Company:
    fields:
        id:
            groups:
                - default
                - company
        name:
            groups:
                - default
                - company
        shortName:
            groups:
                - default
                - company
        address:
            groups:
                - default
                - company
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        createdBy:
            groups:
                - company
        updatedBy:
            groups:
                - company
        deletedBy:
            groups:
                - company
    callbacks: {  }
